version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
    command:
      - /bin/sh
      - -c
      - |
        npx prisma generate
        npx prisma db push
        npx prisma db seed
    ports:
      - '80:3000'
    networks:
      - database

  postgres:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dev!123
      POSTGRES_DB: school-system
    networks:
      - database

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Dev!123
    networks:
      - database

networks:
  database:
