import App, { type AppType } from "next/app";
import { type Session } from "next-auth";
import { getSession, SessionProvider } from "next-auth/react";

import { trpc } from "../utils/trpc";

import "../styles/globals.css";

import { Navigation } from "../components/navigation";
import Head from "next/head";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen flex-col">
        <Navigation items={[]} />
        <main className="h-full w-full px-6">
          <Component {...pageProps} />
        </main>
      </div>
    </SessionProvider>
  );
};

MyApp.getInitialProps = async (context: any) => {
  const appProps = await App.getInitialProps(context);
  const session = await getSession(context);

  console.log(session);

  return {
    ...appProps,
    session,
  };
};

export default trpc.withTRPC(MyApp);
