-- CreateEnum
CREATE TYPE "RoleType" AS ENUM ('ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'DIRECTOR');

-- CreateEnum
CREATE TYPE "PermissionType" AS ENUM ('READ', 'READ_ALL', 'WRITE', 'WRITE_ALL');

-- CreateEnum
CREATE TYPE "ResourceType" AS ENUM ('SCHOOL', 'TEACHER', 'STUDENT', 'USER');

-- CreateTable
CREATE TABLE "School" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "adress" STRING NOT NULL,
    "zip" INT4 NOT NULL,
    "city" STRING NOT NULL,
    "countryCode" STRING NOT NULL DEFAULT 'DK',

    CONSTRAINT "School_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PersonToSchool" (
    "schoolId" UUID NOT NULL,
    "personId" UUID NOT NULL,

    CONSTRAINT "PersonToSchool_pkey" PRIMARY KEY ("schoolId","personId")
);

-- CreateTable
CREATE TABLE "CustodianToPerson" (
    "custodianId" UUID NOT NULL,
    "childId" UUID NOT NULL,

    CONSTRAINT "CustodianToPerson_pkey" PRIMARY KEY ("custodianId","childId")
);

-- CreateTable
CREATE TABLE "Person" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "parentId" UUID,

    CONSTRAINT "Person_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Profile" (
    "id" STRING NOT NULL DEFAULT gen_random_uuid(),
    "firstname" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "age" INT4,
    "phone" STRING,
    "address" STRING,
    "city" STRING,
    "zip" INT4,
    "countryCode" STRING NOT NULL DEFAULT 'DK',
    "personId" UUID NOT NULL,

    CONSTRAINT "Profile_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" STRING NOT NULL,
    "isVerified" BOOL NOT NULL DEFAULT false,
    "password" STRING NOT NULL,
    "personId" UUID NOT NULL,
    "roleId" INT4 NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Role" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" "RoleType" NOT NULL DEFAULT 'STUDENT',

    CONSTRAINT "Role_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RoleToPermission" (
    "roleId" INT4 NOT NULL,
    "permissionId" INT4 NOT NULL,

    CONSTRAINT "RoleToPermission_pkey" PRIMARY KEY ("roleId","permissionId")
);

-- CreateTable
CREATE TABLE "Permission" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "resource" "ResourceType" NOT NULL,
    "type" "PermissionType" NOT NULL,

    CONSTRAINT "Permission_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Profile_personId_key" ON "Profile"("personId");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- AddForeignKey
ALTER TABLE "PersonToSchool" ADD CONSTRAINT "PersonToSchool_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "School"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PersonToSchool" ADD CONSTRAINT "PersonToSchool_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CustodianToPerson" ADD CONSTRAINT "CustodianToPerson_custodianId_fkey" FOREIGN KEY ("custodianId") REFERENCES "Person"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CustodianToPerson" ADD CONSTRAINT "CustodianToPerson_childId_fkey" FOREIGN KEY ("childId") REFERENCES "Person"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Profile" ADD CONSTRAINT "Profile_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoleToPermission" ADD CONSTRAINT "RoleToPermission_permissionId_fkey" FOREIGN KEY ("permissionId") REFERENCES "Permission"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RoleToPermission" ADD CONSTRAINT "RoleToPermission_roleId_fkey" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
